# Generated by Django 3.2.23 on 2023-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
